### PR TITLE
Add output for name of uploaded artifact

### PR DESCRIPTION
**Pull request by rmartin16**
I'd like to avoid needing to assume the name of the artifact in my downstream workflows.

### CODE REVIEW

**Comment by hynek** [comment]
Hi, sorry your work collided with me fixing #123 could you rebase/resolve conflicts? I'll release ASAP then.

**Comment by rmartin16** [comment]
Done. Thank you!

**Comment by hynek** [comment]
Thanks!

**Comment by rmartin16** [comment]
Just as a heads up, I'm about to propose another change. I need to control `check-wheel-contents` to ignore some of it's errors....just in case you'd be willing to entertain that one as well before anther release.

**Comment by hynek** [comment]
I'm afraid further changes will have to wait until after my big vacation. But feel free to open issues/PRs!

**Pull request merged**
