### PR TITLE
Add upload-name-suffix

### LINKED ISSUE #92: FEAT - Allow user to change artefacts name (packages)
eFirst, thanks for creating this super nifty action 🚀  I have found it extremely helpful.

Now, to the feature request.

I have been using this action in a repository with two packages (for various reasons). Both are currently built, inspected, and released within the same workflow (which also builds then some Docker images).

 With the v4 of `actions/upload-artifact`, multiple uploads to the same Artifact are no longer possible. Since this action hardcodes the name within [`Upload built artifacts` step](https://github.com/hynek/build-and-inspect-python-package/blob/88842b6fc4006f618405c1dc0c694afca67ecc58/action.yml#L63) which makes it impossible to use for multiple packages in the same workflow.
 
It seems this would need some changes so that it allows for the user to customise this to allow them to upload multiple artefacts (see example https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md#multiple-uploads-to-the-same-named-artifact)

```yaml
with:
  name: packages-${{ matrix.runs-on }} # or whatever 
```

This might be niche, but if it sounds like a good improvement, I would happily send a PR to add this feature. If not, I will remain in v1 for now.

### PR DESCRIPTION
**Pull request by hynek**
So you can build more than one package per workflow. This also allows us to join our CI workflows again.

Fixes #92

### CODE REVIEW

**Comment by hynek** [comment]
@trallard wdyt?

**Comment by trallard** [comment]
Thank you. This looks good, I can do some testing on my end with this branch tomorrow and circle back with any feedback/findings if any.

**Comment by hynek** [comment]
Cool, thanks! I'll merge it for now, but lmk if anything is awry.

(the rebasing is awkward due to the ci files changes)

**Comment by trallard** [comment]
👍🏽 closing the loop, using this from `main` works like a charm, thank you 🙏🏽

**Pull request merged**
