### PR TITLE
feat: build with uv installs too

### LINKED ISSUE #106: build uv support?
Since uv is already present, what about using `--installer uv` when running build for even more speed? (Requires build 1.2.0, which I released a few minutes ago).

### PR DESCRIPTION
**Pull request by henryiii**
Close #106.

### CODE REVIEW

**Comment by hynek** [comment]
Thanks!

**Comment by henryiii** [comment]
FYI, https://github.com/pypa/build/issues/760 caused me to yank build 1.2.0 but this is locked so should be good. Python 3.11+ should be fine. And 1.2.1 will be out once reviewed (10 hours or so?)

**Comment by hynek** [comment]
Ok I’ll just run the update workflow tomorrow or so

**Comment by henryiii** [comment]
build 1.2.1 is out now. PyPI was blocking all uploads for a bit, but it's out now.

**Pull request merged**
