### PR TITLE
Check old actions runner

### PR DESCRIPTION
**Pull request by ChristopherHX**
You would still need to fix the issues for GHES, but you can now see them in CI.

Feel free to edit my PR.

_please squash merge, if you find it useful_

Seems like you never cleanup `/tmp/baipp` this causes issues on non single use runners, therfore I have enforced job containers.

CI for #37

### CODE REVIEW

**Comment by hynek** [comment]
Ah great thanks! I'll try to get this green! Sorry for the late feedback, I've left for my vacation the day before you opened this PR.

@cmarqu before I start, would the versions this PR tests be good enough for you?

**Comment by cmarqu** [comment]
I'll try tomorrow at work - in the meantime, we have also updated the GHES version from 3.6 to 3.7.

**Comment by hynek** [comment]
There’s nothing to try yet – I’m just wondering if the test matrix would cover your version before I start fixing. :)

**Comment by cmarqu** [comment]
Oops, I wanted to give you an answer here... yes, the test matrix is fine, we are using runner `2.296.3` which is close enough to the `2.296.2` in the workflow.

**Comment by hynek** [comment]
OK I started looking at this and it's just too much pain for me to do to literally make enterprise customers happy. Thank you so much @ChristopherHX providing us with this nugget and if someone decides to finish up the work and / or pay me for this it might work in the future, but as it stands I can't make myself go down this rabbit hole.

I'm OK with leaving this PR open to keep the great work of Christopher around for someone else taking a stab, but if that's annoying for you, feel free to close. I've downloaded and archived the patch locally.

**Pull request closed without merging**
